### ISSUE TITLE
本地调试运行index.php500错误

### ISSUE THREAD

**Issue by Jimmy9876** [lndj/Lcrawl#11]
# git了项目本地运行index.php的时候500error
$stu_id = 'xxxxx';
//your password 
$password = 'xxxxxx';

$user = ['stu_id' => $stu_id, 'stu_pwd' => $password];

$client = new Lcrawl('http://jwxt.xxxx.edu.cn', $user);

$client->login();

$all = $client->setUa('Lcrawl Spider V2.0.2')->getGrade();

print_r($all);
请问是什么原因

**Comment by lndj** [comment]
500 err？ 你指的是教务系统的http code吗？截图看看。

**Comment by Jimmy9876** [comment]
就是我用了你这个爬虫在index.php里改成自己的学号和教务处网站，但是爬下来数据，这是什么情况

**Comment by lndj** [comment]
你也没给地址啥的，我真不知道啊。
