### ISSUE TITLE
问题求教 

### ISSUE THREAD

**Issue by xuzuxing** [lndj/Lcrawl#12]
这边使用新版本的default2.aspx登录  返一直提示密码错误 请问有没有做更新呢，或者是有些什么东西相对来说旧了。谢谢

**Comment by lndj** [comment]
可能不同的学校有些许差异吧，可以附上抓包截图

**Comment by xuzuxing** [comment]
![20180611123610](https://user-images.githubusercontent.com/17402893/41212928-33808f82-6d74-11e8-8f3a-4997994cb2a0.png)

**Comment by xuzuxing** [comment]
也没有多大变化  还有就是  调用登录接口返回的是200  应该是登录成功的

**Comment by lndj** [comment]
验证码的问题吧

**Comment by xuzuxing** [comment]
是啊！！  我怎么忘记验证码这个东西了~我先处理  有问题再向您请教。谢谢你

**Comment by lndj** [comment]
`loginParam` 构造函数的参数 这个是不是传递了

**Comment by lndj** [comment]
![image](https://user-images.githubusercontent.com/9111083/41213001-da30371a-6d74-11e8-9732-66ce184c4835.png)

**Comment by xuzuxing** [comment]
`//The default login post param

        $loginParam = [
            '__VIEWSTATE'       => $viewstate,
            'txtUserName'       => $this->stu_id,
            'TextBox2'          => $this->password,
            'RadioButtonList1'  => iconv('utf-8', 'gb2312', '学生'),
            'Button1'           => iconv('utf-8', 'gb2312', '登录')

        ];

        if (!empty($this->loginParam)) {
            $loginParam = $this->loginParam;
        }

        $query = [
            'form_params' => $loginParam
        ];`

**Comment by lndj** [comment]
是的，登录字段适配

**Comment by xuzuxing** [comment]
不行了，一直登录不上。好难受 ，晚上再找找问题。
