### ISSUE TITLE
跨行没有考虑

### ISSUE THREAD

**Issue by Cheukfung** [lndj/Lcrawl#7]
谢谢你贡献的代码，我自己参考您的代码写了适合我的框架，在写的过程中发现在parserSchedule里面只考虑了2节课连上的情况，而有些学校的课程可能是3节甚至是4节连上。我提个小小的建议，直接把整个表格转为二维数组，这样不仅更有通用性，还更加方便转为大家各自需要的结构，方便存进数据库。
下面是我的方法：
先解析出课表table的全部元素（跨行的元素加上rowspan=x）为二维数组array，然后遍历这个array，如果$array[$i][$j]元素跨行(包含rowspan)，行数为x，则在下一行相同位置（$array[$i+1][$j]）插入该元素。这样的话，即使再复杂的课表跨行，一样可以解析成二维数组。

**Comment by lndj** [comment]
对的～默认忽略了这个，因为都没有遇到过3节这样的情况～～哈哈哈。可以提pr哈～

**Comment by Cheukfung** [comment]
已经提了。另外我参考的时候，我用了Goutte(基于browserkit)这个库，这样的话，可以很大程度模拟浏览器的操作，简化了代码，可以不需要自己buildrequest,不需要自己获取cookie，不需要自己提取viewstate。而且可以通过链接的名称(<a>的value)来获取连接：selectLink(link_value)。这样的话，这个框架可以更加通用，只修要修改：成绩查询 ，就可以查成绩了。不需要担心有什么隐藏字段不一样，因为能通过button获取form

**Comment by lndj** [comment]
嗯，之前看过Goutte，代码很多地方，包括结构还需要优化~ 太忙最近~PR我空下来跑一跑~

**Comment by lndj** [comment]
Merged.
